### PR TITLE
Do not use IPv6 loopback address for next-hop

### PR DESCRIPTION
**Pull request by ton31337**
Do not use IPv6 loopback address for next-hop.

### CODE REVIEW

**Comment by benner** [comment]
Could us use Ohai info avoiding launching external application?

**Comment by ton31337** [comment]
Ohai info you mean `node['ip6address']`?

**Comment by benner** [comment]
AFAIK, Ohai gives route table, interface addreses and so on.

**Comment by ton31337** [comment]
A, good point, I will try

**Pull request closed without merging**
